
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 28 18:43:06 CST 2013
//----------------------------------------------------

package parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 15;
  public static final int CONS = 5;
  public static final int UMINUS = 18;
  public static final int LPAREN = 7;
  public static final int INT = 3;
  public static final int SND = 31;
  public static final int MINUS = 13;
  public static final int RPAREN = 8;
  public static final int NOT = 36;
  public static final int SEMICOLON = 19;
  public static final int AND = 34;
  public static final int LT = 17;
  public static final int FUN = 20;
  public static final int TAIL = 33;
  public static final int NIL = 29;
  public static final int OR = 35;
  public static final int IN = 22;
  public static final int COMMA = 6;
  public static final int PLUS = 12;
  public static final int ASSIGN = 10;
  public static final int IF = 24;
  public static final int ID = 2;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int error = 1;
  public static final int EQ = 9;
  public static final int HEAD = 32;
  public static final int TIMES = 14;
  public static final int ARROW = 11;
  public static final int ELSE = 26;
  public static final int WHILE = 27;
  public static final int LET = 21;
  public static final int THEN = 25;
  public static final int END = 23;
  public static final int FST = 30;
  public static final int GT = 16;
  public static final int DO = 28;
}

